apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:

        - name: pgadmin-container
          image: dpage/pgadmin4
          env:
           - name: PGADMIN_DEFAULT_EMAIL
             value: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
           - name: PGADMIN_DEFAULT_PASSWORD
             value: ${PGADMIN_DEFAULT_PASSWORD:-admin}
           - name: PGADMIN_CONFIG_SERVER_MODE   
             value: 'False'
           - name: PGADMIN_PORT
             value: "${PGADMIN_PORT:-5050}:80"
          ports:
            - containerPort: 80
              name: pgadminport
