apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment
  labels:
    name: postgres-db
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      name: postgres-db
  template: 
    metadata:
      labels:
        name: postgres-db
    spec: 
      containers: 
      - name: postgres
        image: postgres:latest
        ports: 
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "postgres"  
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_DB
            value: todo_db  
            
           