apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoserver-deploy
  labels:
    app: todoserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: todoserver-pod
  template:
    metadata:
      name: todoserver-pod
      labels:
        name: todoserver-pod
    spec:
      containers:
        - name: todoserver
          image: acydevops/todoserver
          ports:
          - containerPort: 8000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/todo_db
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"  
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"



      initContainers:
        - name: init-postgres-service
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-service:5432; do echo waiting for postgres-service; sleep 2; done;']     
           